apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sock-shop-policy
spec:
  podSelector:
    matchLabels:
      app: sock-shop
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: database    # Allow egress to the database pod
    ports:
    - protocol: TCP
      port: 5432         # Allow egress traffic on port 5432 (assuming it's the database port)

