# Default values for sock-shop Helm chart.

# Declare variables to be passed into your templates.

# Replica count for each microservice
replicaCount:
  frontend: 1
  carts: 1
  catalogue: 1
  orders: 1
  payment: 1
  queue-master: 1
  rabbitmq: 1
  shipping: 1
  user: 1

# Service type for each microservice
serviceType:
  frontend: ClusterIP
  carts: ClusterIP
  catalogue: ClusterIP
  orders: ClusterIP
  payment: ClusterIP
  queue-master: ClusterIP
  rabbitmq: ClusterIP
  shipping: ClusterIP
  user: ClusterIP

# Image details for each microservice
image:
  repository: docker.io/your_username/sock-shop 
  tag: "latest"

# External access details for frontend service
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: j3tap.com 
      paths:
        - /

# Database details
mongo:
  enabled: true
  mongodbRootPassword: rootpassword
  mongodbUsername: user
  mongodbPassword: password
  mongodbDatabase: sockshop

# Redis details
redis:
  enabled: true
  usePassword: false

# RabbitMQ details
rabbitmq:
  enabled: true
  rabbitmqUsername: guest
  rabbitmqPassword: guest

# Other configurations
serviceMonitor:
  enabled: true

