---
- name: Deploy Microservices to Kubernetes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Set Kubernetes Context
      k8s_raw:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        resource:
          apiVersion: v1
          kind: Config
          preferences: {}
          current-context: "{{ lookup('env', 'KUBE_CONTEXT') }}"
          clusters:
            - name: "{{ lookup('env', 'KUBE_CLUSTER_NAME') }}"
              cluster:
                certificate-authority-data: "{{ lookup('env', 'KUBE_CA_CERT') }}"
                server: "{{ lookup('env', 'KUBE_SERVER') }}"
          contexts:
            - name: "{{ lookup('env', 'KUBE_CONTEXT') }}"
              context:
                cluster: "{{ lookup('env', 'KUBE_CLUSTER_NAME') }}"
                user: "{{ lookup('env', 'KUBE_USER') }}"
          users:
            - name: "{{ lookup('env', 'KUBE_USER') }}"
              user:
                token: "{{ lookup('env', 'KUBE_TOKEN') }}"
        state: present

    - name: Deploy Frontend Microservice
      k8s:
        state: present
        definition: "{{ lookup('file', 'frontend.yaml') }}"
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"

    - name: Deploy Carts Microservice
      k8s:
        state: present
        definition: "{{ lookup('file', 'carts.yaml') }}"
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"

    - name: Deploy Catalogue Microservice
      k8s:
        state: present
        definition: "{{ lookup('file', 'catalogue.yaml') }}"
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"

    - name: Deploy Orders Microservice
      k8s:
        state: present
        definition: "{{ lookup('file', 'orders.yaml') }}"
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"

    - name: Deploy Payment Microservice
      k8s:
        state: present
        definition: "{{ lookup('file', 'payment.yaml') }}"
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"

    - name: Deploy Queue-master Microservice
      k8s:
        state: present
        definition: "{{ lookup('file', 'queue-master.yaml') }}"
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"

    - name: Deploy RabbitMQ Microservice
      k8s:
        state: present
        definition: "{{ lookup('file', 'rabbitmq.yaml') }}"
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"

    - name: Deploy Shipping Microservice
      k8s:
        state: present
        definition: "{{ lookup('file', 'shipping.yaml') }}"
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"

    - name: Deploy User Microservice
      k8s:
        state: present
        definition: "{{ lookup('file', 'user.yaml') }}"
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"

