apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts
  template:
    metadata:
      labels:
        app: carts
    spec:
      containers:
      - name: carts
        image: weaveworksdemos/carts:0.4.8
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: carts
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: carts
