apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: weaveworksdemos/payment:0.4.8
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: payment