apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: weaveworksdemos/user:0.4.8
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: user